### ISSUE TITLE
Running SI with Harder Wildlife is unplayable in standard configuration

### ISSUE THREAD

**Issue by SvenKayser** [reteo/Survival-Industry#101] opened 2016-10-18 14:16 UTC
The issue here is the tree handling. Even on a moderately fat workstation (Xeon E5-1650 Hexacore) the tree decay code completely renders a SSP game unplayable. I know that HarderWildlife isn't part of the standard config any more, but I think it should be disabled by default regardless.

**Comment by reteo** [comment] 2016-10-18 14:18
Unplayable how?  What's happening?

**Comment by SvenKayser** [comment] 2016-10-18 18:33
Like I said I know it's disabled by default - but it's still an enticing part of the game at least to me. And as long as it's optionally in the pack I would say it should be maintained as part of it.

Unplayable how..... the event handler that takes care of tree age and automatic tree decay spikes exceptionally high especially on newly generated chunks, up to a degree where breaking a block in a forested areas easily takes a few tries. The setting in question is `B:trackTrees=true
` ... disabling it solves the problem immediately.

**Comment by reteo** [comment] 2016-10-18 19:14
You're saying that's the tree handler?  Huh; I had been under the impression it was the ore handler.  Part of the reason I avoided adding world generation mods as a default feature.  You might also want to report this to Draco in the [Reasonable Realism thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2451299-reasonable-realism-its-a-pack-its-a-mod-it-makes?page=52).

**Comment by reteo** [comment] 2016-10-19 22:41
Okay, configuration has changed.  Go ahead and reinstall to confirm that the issue is resolved.

**Comment by SvenKayser** [comment] 2016-10-24 05:46
Yeah, this solves that. I'll leave this open here until I actually have some deeper analysis of this and gave some intelligble info to Draco

**Comment by reteo** [comment] 2016-11-22 19:48
I think I can safely close this.  Once we have the ability to add the tree handler back, we can simply create a new issue.

**Closed by reteo** 2016-11-22 19:48 UTC
