### ISSUE TITLE
Unable to craft and use items

### ISSUE THREAD

**Issue by jmcaffee** [reteo/Survival-Industry#47] opened 2015-12-01 16:56 UTC
I am unable to craft and use any crafted items.

OS: Ubuntu 15.04
MC: 1.7.10
Mod Pack: Survival Industry v1.3.0

Scenario 1:
- in the personal crafting grid (2x2), craft planks, craft a crafting table, place table in inventory
- close inventory
- open inventory, crafting table is gone, log count is back to starting count as if planks and table were never created

Scenario 2:
- in the personal crafting grid (2x2), craft planks, craft a crafting table, place table in hot bar
- close inventory
- select item in hot  bar and right click on ground to place table
- table is visible for a second then disappears

Scenario 3:
- cheat mode is on
- give myself a crafting table (eg. /give USER 58 1)
- place table (works)
- use table (works)

I've googled and browsed to see if there's a restriction on using/making crafting tables and from the FAQ it seems as if there's not. 

I'm running other mod packs (Infinity, Regrowth, custom, etc) with no issues. Any idea as to what's going on?

**Comment by Rewyn** [comment] 2015-12-01 18:56
Hm. Can't reproduce at all with a clean installation.
Tried redownloading the whole pack, in case your download was corrupted?
What Java version are you using?
I assume just making planks isn't possible either and they revert bacl to wooden logs?
Also going by the title, this problem happens with all kind of crafted items?
Title says you're unable to use items, does this refer to tools and the like? Since you said using the crafting table works in scenario 3.

**Comment by reteo** [comment] 2015-12-01 19:41
Are you playing SSP or SMP?

**Comment by jmcaffee** [comment] 2015-12-01 19:43
Playing SSP. I've redownloaded the pack using the FTB Launcher `force`

**Comment by jmcaffee** [comment] 2015-12-01 19:59
Moved the directory and re-downloaded a fresh copy... same issues.

**Comment by reteo** [comment] 2015-12-01 20:03
Interesting.  I've just created a fresh game, and have crafted and placed the table with no issues.  Of course, I'm using 14.04LTS, but there shouldn't be that big a difference, I don't think.

Which version of Java are you using?  Are you using OpenJDK or Oracle?  Are you using any custom options?  How much memory are you giving the launcher in the options tab?

**Comment by jmcaffee** [comment] 2015-12-02 03:04
No custom options. FTB is set to 2GB but I also ran it via MultiMC with 3.75GB and got the same result.

Ok. Downloaded 1.2.0 and it works fine.

I noticed a difference between the two versions though:

1.2.0: The inventory screen shows the tabs, with the swords and shield tab as the 3rd tab from the left and the default page is the crafting table.

1.3.0: The inventory screen does **not** show tabs, instead, there are 2 buttons to the left in vertical array. Button 1 says "BG" and Button 2 says "Sigil" (there may be more text on the button but it's cut off). The default page is the swords page. Clicking "BG" displays the crafting grid.

**Comment by reteo** [comment] 2015-12-02 03:07
Actually, the reason for that is that 1.3.0 had removed Tinker's Construct, which had provided those tabs.

**Comment by reteo** [comment] 2015-12-02 04:29
I'm stumped; it seems to be something inside your system that's blocking the game.  Can you post the log here?  Maybe there'll be a hint to the problem in there.

**Comment by Rewyn** [comment] 2015-12-02 15:00
Would it be possible to upload the 1.3.0 version that doesn't work somewhere?
Not sure if there's an actual point in that, but I don't have any others ideas at the moment.

**Comment by reteo** [comment] 2015-12-02 18:02
Actually, from the sound of it, he's using the cleanly installed version; the problem is likely a system issue.  I suspect either a problem with the installed version of Java, or perhaps a permissions issue with the OS.

**Comment by Rewyn** [comment] 2015-12-02 21:37
Yea, i got that. Just thought there may be something wrong with his download altogeher. Had an ISP issue some time ago, where half of the downloads I did for a few days all were corrupted in some way.
This is mainly me grasping at straws, tho.

**Comment by reteo** [comment] 2015-12-03 00:27
Corrupted downloads usually means either a Minecraft crash, or random errors on each install.  The consistency of this issue precludes corruption during the download process.  Because of that, the problem has to exist every single time the game is installed and run.  The easiest way to check this is to take the downloaded copy of Feed the Beast, zip it up, and transfer it to another computer to see if the issue persists.

**Comment by Rewyn** [comment] 2015-12-03 08:24
Well yea. That's about what I thought/said.

**Comment by reteo** [comment] 2015-12-24 03:52
It's been nearly a month with no further response.  Closing the ticket.  If any more issues surface like this one, the ticket will be re-opened.

**Closed by reteo** 2015-12-24 03:52 UTC
Labels: cannot reproduce
