### ISSUE TITLE
Missing WAILA information for ReactorCraft Blocks (was: More WAILA issues)

### ISSUE THREAD

**Issue by Rewyn** [reteo/Survival-Industry#3] opened 2015-09-14 16:50 UTC
WAILA doesn't show temperature and Tank1 (Hot co2) Carbon Dioxide Heat Exchanger.
Workaround by disabling WAILAPlugins.
ver 1.1.2

**Comment by reteo** [comment] 2015-09-14 16:56
The issue has been submitted to Reika, who is working to resolve it.

**Comment by gerb82** [comment] 2015-09-14 16:58
between, is there a way i could also manage tags and things so i can also close and open issues and things like that?

**Comment by reteo** [comment] 2015-09-14 17:02
Hopefully, that should do it.

**Comment by reteo** [comment] 2015-09-15 00:06
Let's keep this open until the issue is actually resolved. ;)

**Comment by reteo** [comment] 2015-10-09 23:52
Issue resolved with 1.2.0

**Closed** 2015-10-09 23:52 UTC
Labels: bug, escalation

**Comment by reteo** [comment] 2015-10-09 23:53
Issue resolved with 1.2.0.
