### ISSUE TITLE
Starting server(AtLauncher) crashes with Exception in server tick loop. Update 1.4.0

### ISSUE THREAD

**Issue by Quantarious** [reteo/Survival-Industry#83] opened 2016-02-17 18:57 UTC
As it says in the title, the server crashes, it's the latest version server I see in the launcher and have had issues with mods causing this kind of crash but I was wondering if someone could help me find a temporary fix because I would really like to play on this pack with my cousin. Here is my crash report

[crash-2016-02-17_12.48.24-server.txt](https://github.com/reteo/Survival-Industry/files/134974/crash-2016-02-17_12.48.24-server.txt)

**Comment by reteo** [comment] 2016-02-17 21:13
This is a duplicate of #75.  The short of it is that the "si.core" mod (the "Survival Industry Mod") does not work in servers at this time.  However, version 1.5 should be released in the next couple days, and the server has been explicitly tested and verified as working.

**Closed** 2016-02-17 21:18 UTC
Labels: Duplicate
