### ISSUE TITLE
Battlegear Wooden Shield 'free' recipe intended?

### ISSUE THREAD

**Issue by Dulciphi** [reteo/Survival-Industry#58] opened 2016-01-14 20:16 UTC
currently the Wooden shield is "ready-crafted" and waiting for me whenever I right click the vanilla crafting table. I was able to remove the free shield from the crafting table and equip it. Opening the vanilla crafting table a second time produces another. It seems as if the recipe for the shield is all null, and in fact NEI shows that to be the case. That isn't what's shown in the Minetweaker scripts, though.

It should be
recipes.addShaped(<battlegear2:shield.wood>, [[null, planks, null],[planks, wood, planks],[null, planks, null]]);

**Comment by Dulciphi** [comment] 2016-01-14 20:27
Just confirmed this in a new instance of AstralAcorn using Recommended set up. Had nothing in my inventory besides the starting inventory of a sleeping bag.

The 'free' recipe is *not* craftable in the 2x2 grid inside player inventory.

**Comment by reteo** [comment] 2016-01-14 23:13
Hmmm... interesting.  Thanks for the heads-up.  I'll take some time to go through these and make sure all values are set in their respective scripts.

**Comment by reteo** [comment] 2016-01-15 02:56
Okay, the problem is now fixed; all variables have been added to the configurations.  The phantom shield no longer manifests in the empty table.

**Closed by reteo** 2016-01-15 02:56 UTC
